### ISSUE TITLE
./x10 can not run

### ISSUE THREAD

**Issue by MasamiYOYO** [x10-lang/x10#12]
Hello,when I run a HelloWorld program.I meet a problem,
./x10: line 364: /home/caofanglin/x10-master/x10-master/x10.dist/bin/X10Launcher: No such file or directory
./x10: line 364: exec: /home/caofanglin/x10-master/x10-master/x10.dist/bin/X10Launcher: cannot execute: No such file or directory
I don't know where I am wrong.Could you help me,please?

**Comment by mtake** [comment]
Before trying to build from source, I recommend to use prebuilt binary and make sure you can successfully run your program with it.   You can download the prebuilt binary for your platform at http://x10-lang.org/software/download-x10/latest-release.html .
For building X10 from source, please follow the instruction in http://x10-lang.org/x10-development/building-x10-from-source.html .  Once your build is successful, x10.dist/bin/X10Launcher should be there.

**Comment by MasamiYOYO** [comment]
Thank you very much.The reason is that I didn't install  g++.Thank you!!!
