### ISSUE TITLE
x10c++: nvcc fatal : Value 'sm_30' is not defined for option 'gpu-architecture'

### ISSUE THREAD

**Issue by vahya** [x10-lang/x10#35]
I've built x10 from source with the ``-DX10RT_CUDA=true -Doptimize=true`` options and the build was successful, but when I try to run the sample CUDA programs, I get the following error:
```
x10c++: nvcc fatal : Value 'sm_30' is not defined for option 'gpu-architecture'    
x10c++: Non-zero return code: 1
x10c++: Found @CUDA annotation, but compilation of CUDAMatMul.cu with nvcc -arch=sm_30 failed.
3 errors.
```
I've googled but found nothing. How do I fix this?

I have an Nvidia GeForce GTX 1050 laptop, and ``nvcc --version`` shows:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```

**Comment by dgrove-oss** [comment]
The CUDA backend for X10 hasn't been maintained for years.  That being said, you might be able to get around this by updating the code here https://github.com/x10-lang/x10/blob/master/x10.compiler/src/x10cpp/postcompiler/CXXCommandBuilder.java#L428-#L467 that tries to figure out the CUDA architecture.

**Comment by vahya** [comment]
I just commented all the lines in ``CXXCommandBuilder.java`` file and added ``ans.add("sm_61")`` and it worked.
Thanks for the response.
