### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ghost** [x10-lang/x10#37]
I found it on the list of JVM languages on Wikipedia:

https://en.wikipedia.org/wiki/List_of_JVM_languages

I searched and found this GitHub repository. It seems the project is dead. The website for it (x10-lang.org) doesn't even have https. Given the number of stars this repository has, I think this language has never been popular. The most recent submitted issue doesn't have any replies and the last activity was from 2021.

I will try to tag the developers to hear something official from you. Sorry for bothering you all.

@bherta @dgrove-oss @mandel @michihirohorie @mtake @tardieu

**Comment by dgrove-oss** [comment]
The X10 Research project ended a numbers of years ago.  There is no active work maintaining it.
